// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TE3bnLBpC2L0IjuLBWOoQ5D-Co3ADNU',
    appId: '1:310909747679:web:18da67c965d1812134c46a',
    messagingSenderId: '310909747679',
    projectId: 'sabo-96f81',
    authDomain: 'sabo-96f81.firebaseapp.com',
    storageBucket: 'sabo-96f81.firebasestorage.app',
    measurementId: 'G-5BYGST2XRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjbX_5-85kABj8myjL48A3WLWqvT5haI',
    appId: '1:310909747679:android:0515add487ce67a934c46a',
    messagingSenderId: '310909747679',
    projectId: 'sabo-96f81',
    storageBucket: 'sabo-96f81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85CCc3iLg7cI9CWICqcmiBEJal1upXa4',
    appId: '1:310909747679:ios:fc10d14f0a57dc1a34c46a',
    messagingSenderId: '310909747679',
    projectId: 'sabo-96f81',
    storageBucket: 'sabo-96f81.firebasestorage.app',
    iosBundleId: 'com.example.manhajulIhsanFoundation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85CCc3iLg7cI9CWICqcmiBEJal1upXa4',
    appId: '1:310909747679:ios:fc10d14f0a57dc1a34c46a',
    messagingSenderId: '310909747679',
    projectId: 'sabo-96f81',
    storageBucket: 'sabo-96f81.firebasestorage.app',
    iosBundleId: 'com.example.manhajulIhsanFoundation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5TE3bnLBpC2L0IjuLBWOoQ5D-Co3ADNU',
    appId: '1:310909747679:web:dc44de2b6e2c584734c46a',
    messagingSenderId: '310909747679',
    projectId: 'sabo-96f81',
    authDomain: 'sabo-96f81.firebaseapp.com',
    storageBucket: 'sabo-96f81.firebasestorage.app',
    measurementId: 'G-DBHCYBMLFF',
  );
}
